:PROPERTIES:
:ID: 3533978f-e35f-4b28-8af0-8fa8e2d618fb
:END:
#+title: Lógica Digital
#+filetags: :MOC:

* Lógica Digital
Lógica Digital é a disciplina que introduz a base para qualquer conceito relacionado a circuitos digitais. O curso todo foi baseado no livro [[file:attachments/Fundamentals_of_Digital_Logic.pdf][Fundamentals of Digital Logic]]. As notas estão organizadas de acordo com os capítulos e seções do livro.

** Chapter 1
This chapter introduces the process of designing digital circuits, as well as the [[id:63384077-a1b3-4e87-ba0b-d3721c8c0102][digital representation of information]].

** Chapter 2
This chapter is where things really start, it introduces the fundamental concepts to design digital circuits:

[[id:2fae20b7-7f7a-42e4-b379-a0a3cfa967f6][Logic functions]]
[[id:1a9b753e-e05d-4dba-85a0-b18d6583a7d3][Boolean algebra]]
[[id:32037cd8-306b-4498-8cb2-fdf26754086f][Logic synthesis]]
[[id:73012c9b-f3c0-4379-ba84-831aa20e8f1b][Introduction to Verilog]]

** Chapter 3 (sections 3.1 to 3.5)
This chapter presents the topics involving arithmetic circuits and operations:

[[id:4d663191-e9a5-4704-b79c-a8fa087e7fd1][Positional number representation]]
[[id:3541d72a-41db-4950-93a1-4814edb16f7d][Arithmetic logic circuits]]
[[id:d482f0df-3203-4a84-bfed-94344bc062e2][Arithmetic circuits in Verilog]]
[[id:08b94d05-8f82-4c76-8eb9-d24e8a777f79][Representation of numbers in Verilog]]

** Chapter 4
This chapter presents some interesting combinational circuits:

[[id:7df44724-50a7-4711-b3e8-85b228eb3bae][Multiplexers]]
[[id:21ae386f-3c92-4233-b672-06c5a03f6210][Encoders and decoders]]

** Chapter 5
Here we were introduced to circuits that can store information, these circuits are called [[id:b1e8ff6d-8a21-4a9c-ae1b-6d1ddb84bd6f][sequential circuits]]. We also were introduced to the different elements that are used to store information:

[[id:4f33c7ad-e863-404d-b011-eb7793459a48][Latches]]
[[id:a6be1dd8-a863-484f-bc34-6334be627728][Propagation delay]]
[[id:860d0638-e241-4bcc-b6a7-1fab58f2ed36][Flip-Flops]]
[[id:6ca9dde1-6128-4fd1-bd48-a943ca3bfd3b][Registers]]
[[id:5b18c678-59be-4c72-8296-8a756de6ede9][Counters]]
[[id:bb43580a-a618-416f-a346-39f9d8059491][Implementation of storage in Verilog]]
[[id:e4bcd3c6-e616-4d65-8fdf-9431c8b5d893][Non-blocking assignments]]
[[id:15cbfe06-523b-4b50-b140-d2094528d890][Timing analysis]]

** Chapter 6
In this chapter we continue to explore the [[id:b1e8ff6d-8a21-4a9c-ae1b-6d1ddb84bd6f][sequential circuits]], learning more formal ways of describing those circuits and new design techniques.
[[id:192a60c8-c700-4145-8a73-367bc1599eee][Finite state machines]]
[[id:fce93cd2-8d92-4cdf-9332-64a590d91efa][State diagram and table]]
[[id:71c7f6ff-9547-4182-ad7c-678c21fadb13][Designing sequential circuits]]
[[id:de1fbfbf-a8b8-4ff8-933e-05e57e291903][Finite state machines in Verilog]]
[[id:6566fdcf-a1c1-46ec-8e54-e859e9961ecd][State minimization]]

** Chapter 7
In the final chapter covered by the course, we are presented to some more aspects of digital systems.
[[id:95e22236-d77f-4b59-ab0c-97a3c3a229ed][Bus structure]]

--------------
