:PROPERTIES:
:ID: bb43580a-a618-416f-a346-39f9d8059491
:END:
#+title: Implementation of storage in Verilog

The different elements that allow us to storage data in digital circuits can be implemented quite easily with the use of =if-else= statements. Here we find the [[id:73012c9b-f3c0-4379-ba84-831aa20e8f1b][verilog ]] examples for the basic structures of storage.

* Latches
[[id:4f33c7ad-e863-404d-b011-eb7793459a48][Latches]] can be described in a simple way using a =if= statement. Here is a example a [[id:d075714a-a86f-4dcc-878d-9c5d2cdf9413][gated D latch]] module

#+begin_src verilog
module D_latch(D, Clk, Q);
    input D, Clk;
    output reg Q;
    
    always @(D, Clk)
        if(Clk)
            Q = D;
endmodule
#+end_src

* Flip-flops
For [[id:860d0638-e241-4bcc-b6a7-1fab58f2ed36][flip-flops]] we have to use the =posedge= and =negedge= keywords, these keywords describe the desired clock edge that trigger the evaluation of the expression.

#+begin_src verilog
module flipflop(D, Clock, Q);
    input D, Clock;
    output reg Q;
    
    always @(posedge Clock)
        Q = D;
endmodule
#+end_src

* Registers and Counters
To describe [[id:5b18c678-59be-4c72-8296-8a756de6ede9][counters ]] and [[id:6ca9dde1-6128-4fd1-bd48-a943ca3bfd3b][registers ]] we have to use the [[id:e4bcd3c6-e616-4d65-8fdf-9431c8b5d893][non-blocking assignments]], otherwise we'll end up with a circuit that doesn't make sense.

** Registers
Here we can see a example of a general /n-bit/ register with /asynchronous/ clear:

#+begin_src verilog
module nbit_register(D, Clock, Resetn, Q);
  parameter n = 16; //The desired value
  input [n-1:0] D;
  input Clock, Resetn;
  output reg [n-1:0] Q;

  always @(negedge Resetn, posedge Clock)
    // Check if we should reset or just load the value
    if(!Resetn)
      Q <= 0;
    else
      Q <= D;
endmodule
#+end_src

A general description for a /n-bit/ parallel-access shift register can be done like the following example:

#+begin_src verilog
module nbit_shifter_load(R, L, w, Clock, Q);
  parameter n = 16; // The desired value
  input [n-1:0] R;
  input L, w, Clock;
  output reg [n-1:0] Q;
  integer k;

  always @(posedge Clock)
    // Checks if we should shift or load from the input
    if(L)
      Q<=R;
    else
      // Create n flip-flops for the register
      begin
        for(k=0;k<n-1;k=k+1)
          Q[k]<=Q[k+1];
        Q[n-1]<=w;
      end
endmodule
#+end_src

** Counters
We can describe a generic /up/down/ counter with load capability like this:

#+begin_src verilog
module updown_n_count(R, Clock, L, E, up_down, Q);
  parameter n = 8; // The desired value
  input [n-1:0] R;
  input Clock, L, E, up_down;
  output reg [n-1:0] Q;

  always @(posedge Clock)
    // Checks if we should count or load from the input
    if(L)
      Q<=R;
    else if(E)
      Q<=Q+(up_down ? 1:-1);
endmodule
#+end_src
