:PROPERTIES:
:ID:       4d2791ad-0f96-44e3-8f2d-0779fcc26049
:END:
#+title:Linguagens regulares

Linguagens regulares são [[id:70808c19-0237-4a2e-8a09-d003667c1278][linguagens formais]] geradas por [[id:304e4812-6121-4b07-b0a3-6ef140afa799][gramáticas regulares]]. De acordo com a [[id:ec1b6263-ac3c-4392-a383-76acacea4375][Hierarquia de Chomsky]], as linguagens regulares compõe a classe mais *simples* de linguagens. Isso implica que é possível desenvolver algoritmos de reconhecimento, geração ou conversão entre os formalismos dessas linguagens de *pouca complexidade*, *alta eficiência* e *fácil implementação*.

Devido à sua simplicidade, as linguagens regulares possuem *limitações de expressividade*. A maioria das linguagens de programação de propósito geral não são regulares, pois não é possível expressá-las através de uma linguagem regular. Entretanto, devido à simplicidade e fácil implementação de algoritmos que manipulam essas linguagens, as linguagens regulares são usadas extensivamente na computação. Alguns exemplos comuns de uso de linguagens regulares são a análise léxica dos compiladores, sistemas de animação, hipertextos e hipermídias.

As linguagens regulares possuem propriedades que às relacionam com outros formalismos. Toda linguagem regular satisfaz as seguintes propriedades:

- Ela pode ser *gerada* por uma [[id:304e4812-6121-4b07-b0a3-6ef140afa799][Gramática Regular]];
- Ela pode ser *reconhecida* por um [[id:ec2b2e55-5924-4dc8-a3d3-2996dada0273][Autômato Finito]];
- Ela pode ser *descrita* por uma [[id:71d4f8cb-e496-4bb8-8577-09cbddc4c9c7][Expressão Regular]].

Uma característica importante dessa classe de linguagens é que ela é fechada para algumas operações, dentre elas a *união*, *concatenação*, *complemento* e *intersecção*. Portanto, dadas duas linguagens regulares, aplicar a elas quaisquer uma dessas quatro operações resulta em uma outra linguagem regular.
