:PROPERTIES:
:ID:       34633935-cf83-42e7-8927-ede9f7bc29e2
:END:
#+title:Programação Paralela e Distribuída
#+filetags: :MOC:

A programação paralela e distribuída explora técnicas de desenvolvimento com a finalidade de *extrair ao máximo* os recursos de sistemas computacionais modernos, o que geralmente envolve utilizar *múltiplas unidades de processamento* ao mesmo tempo.

Com o avanço do desenvolvimento de processadores, as limitações físicas dificultam cada vez mais o desenvolvimento de unidades de processamento mais poderosas. Para contornar essa limitação, sistemas computacionais modernos fazem uso de diversas unidades de processamento. Isso resulta não só em processadores com *múltiplos cores*, mas também em *unidades de processamento vetoriais*, *clusters* de processamento que agregam diversos computadores em uma única rede etc.

Para explorar múltiplas unidades de processamento, é necessário empregar técnicas de *decomposição*, *distribuição* e *coordenação* no desenvolvimento do programa, geralmente dividindo o problema em diversas partes que podem ser executadas de forma *simultânea* e *coordenada* por diversas unidades de processamento.

[[id:7a7071fe-2c38-4e25-adac-fe35b7f2353e][Modelos de programação paralela]]
[[id:7a20cfd9-e3d9-413c-b712-6bd204ee410f][Granularidade de paralelismo]]
[[id:bd1562aa-5a81-4046-9cad-e8d647b879ea][Projeto de programas paralelos]]
[[id:e48742bd-00e8-4d60-a43e-b5326e4b48d7][OpenMP]]
[[id:ba968b37-a693-4616-8058-90b90ae49e71][Processamento vetorial]]
[[id:7bc12118-c016-4226-aab7-9dc31f81a7e3][MPI]]
