:PROPERTIES:
:ID:       856567a0-553e-43d8-ae90-66061ad93262
:END:
#+title: Gramática

Uma gramática é um formalismo axiomático de geração que permite *derivar* todas as palavras da [[id:70808c19-0237-4a2e-8a09-d003667c1278][linguagem]] que representa. Pode-se definir uma gramática como uma tupla de $4$ elementos na forma: $G = (V, T, P, S)$ tais que:

- $V$ é um conjunto finito de [[id:f8a4e91c-078f-433c-9be4-fb1f4b9d064e][símbolos]] *variáveis* ou não-terminais
- $T$ é um conjunto finito de [[id:f8a4e91c-078f-433c-9be4-fb1f4b9d064e][símbolos]] *terminais*  (disjunto de $V$)
- $P$ é um conjunto finito de pares $(\alpha, \beta)$ de *regras de produção*, sendo que $\alpha$ é uma [[id:2e1e038b-f30b-48bb-8d43-0fdae3f0afba][palavra]] de $(V \cup T)^+$ e $\beta$ é uma [[id:2e1e038b-f30b-48bb-8d43-0fdae3f0afba][palavra]] de $(V \cup T)^*$.
- $S$ é um elemento de $V$ chamado *variável inicial*.

Dada uma gramática $G = (V,T,P,S)$, uma [[id:70808c19-0237-4a2e-8a09-d003667c1278][linguagem]] gerada por $G$, denotada por $L(G)$ é composta por todas as [[id:2e1e038b-f30b-48bb-8d43-0fdae3f0afba][palavras]] de *símbolos terminais* deriváveis a partir do símbolo inicial $S$, ou seja:

$$
L(G) = \{w \in T^* | S \Rightarrow^+ w\}
$$

Duas gramáticas $G1$ e $G2$ são equivalentes se e somente se ambas geram a mesma [[id:70808c19-0237-4a2e-8a09-d003667c1278][linguagem]], ou seja, se $L(G1) = L(G2)$.

Uma cadeia $w \in T^*$ é dita uma *sentença* da gramática $G=(V,T,P,S)$ se e somente se $S \Rightarrow^* w$, ou seja, se $w$ é uma cadeia formada apenas de símbolos terminais e pode ser obtida a partir do símbolo $S$ da gramática $G$ por meio de sucessivas derivações.

Uma cadeia $\alpha \in (V \cup T)^*$ é dita *forma sentencial* da gramática $G=(V,T,P,S)$ se e somente se $S \Rightarrow^* \alpha$, ou seja, $\alpha$ é uma palavra formada por símbolos variáveis ou terminais (ou ambos). Sendo assim, uma forma sentencial é um dos passos intermediários para alguma sentença gerada pela gramática, ou a própria sentença.
