#+title: Algoritmos e Estruturas de Dados

As estruturas de dados visam organizar dados de forma a fornecer um conjunto de operações sobre os mesmos de maneira eficiente. Já os algoritmos em geral manipulam estruturas de dados para resolver algum problema em específico. Sendo assim, o objetivo da disciplina é fornecer uma visão teórica e prática de diversos algoritmos e estruturas de dados, bem como as ferramentas para realizar a análise de desempenho dos mesmos.

* Tabelas de símbolos
Uma tabela de símbolos (ou dicionários) é uma estrutura de dados abstrata que armazena um conjunto de itens, no qual cada item possui um valor e uma *chave* associada. O principal propósito de uma tabela de símbolos é permitir o *acesso* eficiente *ao valor* de um elemento a partir de sua *chave* associada.

Além da operação de busca por chave, tabelas de símbolos comumente oferecem algumas outras operações que permitem a manipulação dos elementos, como operações inserção e remoção.

A implementação de uma tabela de símbolos pode ser dada através de diversas estruturas de dados, mas as estruturas mais utilizadas são as *árvores binárias de busca* e as *hash tables*.

** Árvores binárias
*** Árvores AVL
** Skip lists
** Hash tables

* Ordenação
** Merge sort
** Quick sort
** Counting sort
** Radix sort

* Busca de palavras
* Busca em grafos
