:PROPERTIES:
:ID: cfd9b049-6a5d-4d7a-b7b8-ef7d5ba84106
:END:
#+title: Convergência de séries

* Convergência de séries
Uma forma imediata de verificar se uma [[file:Séries numéricas .org][ série]] diverge ou converge é verificar se seu termo geral \(a_n\) converge a \(0\).

#+begin_quote
*/Critério do termo geral/*
Dada uma série \(S = \displaystyle\sum_{n=1}^{\infty}{a_n}\). Se \(S\) converge, então \(\displaystyle\lim_{n \to \infty} a_n = 0\).

#+end_quote

Note que a recíproca dessa condição não é válida, ou seja, existem sequências convergem a \(0\) cuja soma não é convergente.

** Critérios de convergência
Além da verificação pelo termo geral, existem muitas outras formas de verificar a convergência de séries, algumas delas são enunciadas aqui.

[[id:c443b709-290e-4ea7-a3db-772e44598730][Critério da comparação]]
[[id:f25859bf-25fb-4afe-8aaf-580400f4cad3][Critério da integral]]
[[id:3dc5b7cc-654a-4a8b-941d-537dd2830dfa][Critério da raiz]]
[[id:f383f004-ed83-4cb9-80f5-4421c454cc0d][Critério da razão]]
[[id:e178d131-ccd8-498b-8b7e-792245a24557][Critério de Leibniz]]

** Convergência absoluta e condicional

#+begin_quote
*/Convergência absoluta/*
Uma série \(\displaystyle\sum_{n = 1}^{\infty}{a_n}\) é /absolutamente convergente/ se a série correspondente de valores absolutos \(\displaystyle\sum_{n = 1}^{\infty}{|a_n|}\) converge.

#+end_quote

#+begin_quote
*/Convergência condicional/*
Uma série que converge, mas não converge absolutamente, isto é, a série correspondente de valores absolutos diverge, é chamada de /condicionalmente convergente/.

#+end_quote

Os conceitos de convergência absoluta e convergência condicional nos permitem, além de classificar séries, estender os critérios de convergência de séries de termos positivos para qualquer série com qualquer distribuição de sinal entre seus termos.

#+begin_quote
*/Teste da convergência absoluta/*
Se \(\displaystyle\sum_{n = 1}^{\infty}{|a_n|}\) converge, então \(\displaystyle\sum_{n = 1}^{\infty}{a_n}\) converge.

#+end_quote

É importante ressaltar que a recíproca desse teste *não* é válida, ou seja, é possível que uma série convergente não seja absolutamente convergente (a série harmônica alternada é um exemplo desse fenômeno).

--------------

created: 28/08/2021
