:PROPERTIES:
:ID: CFD9B049-6A5D-4D7A-B7B8-EF7D5BA84106
:END:
#+title: Convergência de séries

* Convergência de séries
Uma forma imediata de verificar se uma [[file:Séries numéricas .org][ série]] diverge ou converge é verificar se seu termo geral \(a_n\) converge a \(0\).

#+begin_quote
*/Critério do termo geral/*
Dada uma série \(S = \displaystyle\sum_{n=1}^{\infty}{a_n}\). Se \(S\) converge, então \(\displaystyle\lim_{n \to \infty} a_n = 0\).

#+end_quote

Note que a recíproca dessa condição não é válida, ou seja, existem sequências convergem a \(0\) cuja soma não é convergente.

** Critérios de convergência
Além da verificação pelo termo geral, existem muitas outras formas de verificar a convergência de séries, algumas delas são enunciadas aqui.

[[id:C443B709-290E-4EA7-A3DB-772E44598730][Critério da comparação]]
[[id:F25859BF-25FB-4AFE-8AAF-580400F4CAD3][Critério da integral]]
[[id:3DC5B7CC-654A-4A8B-941D-537DD2830DFA][Critério da raiz]]
[[id:F383F004-ED83-4CB9-80F5-4421C454CC0D][Critério da razão]]
[[id:E178D131-CCD8-498B-8B7E-792245A24557][Critério de Leibniz]]

** Convergência absoluta e condicional

#+begin_quote
*/Convergência absoluta/*
Uma série \(\displaystyle\sum_{n = 1}^{\infty}{a_n}\) é /absolutamente convergente/ se a série correspondente de valores absolutos \(\displaystyle\sum_{n = 1}^{\infty}{|a_n|}\) converge.

#+end_quote

#+begin_quote
*/Convergência condicional/*
Uma série que converge, mas não converge absolutamente, isto é, a série correspondente de valores absolutos diverge, é chamada de /condicionalmente convergente/.

#+end_quote

Os conceitos de convergência absoluta e convergência condicional nos permitem, além de classificar séries, estender os critérios de convergência de séries de termos positivos para qualquer série com qualquer distribuição de sinal entre seus termos.

#+begin_quote
*/Teste da convergência absoluta/*
Se \(\displaystyle\sum_{n = 1}^{\infty}{|a_n|}\) converge, então \(\displaystyle\sum_{n = 1}^{\infty}{a_n}\) converge.

#+end_quote

É importante ressaltar que a recíproca desse teste *não* é válida, ou seja, é possível que uma série convergente não seja absolutamente convergente (a série harmônica alternada é um exemplo desse fenômeno).

--------------

created: 28/08/2021
