:PROPERTIES:
:ID: 0A25C6F1-3AD2-4A2A-BA1B-05BA2AC6FCE1
:END:
#+title: Indutivismo
#+filetags: :Argumentos:

* Indutivismo
O indutivismo é uma concepção de ciência que considera que todo conhecimento científico tem origem na observação e na experiência. Ele tem sua base no [[file:Indução .org][ raciocínio indutivo]].
Há alguns pressupostos no indutivismo quanto à natureza dos dados coletados empiricamente:

1. O observador deve ser capaz de registrar fielmente aquilo que detecta com seus sentidos.
2. O registro obtido deve ser inteiramente objetivo e livre de preconceitos.

Para o indutivista, é legítimo *generalizar*, ou seja, a partir de uma quantidade finita de proposições singulares criar uma lei universal que valha para todos os casos.
Existem algumas condições para que um raciocínio seja legítimo na visão indutivista:

1. O número de proposições que forma a base de uma generalização deve ser grande.
2. As observações devem ser repetidas sob uma ampla variedade de condições.
3. Nenhuma proposição de observação deve conflitar com a lei universal que se deriva dela.

Uma vez derivada uma teoria ou lei a partir da indução, há ainda o processo de /dedução/, que consiste em explicar e prever fenômenos. O *raciocínio dedutivo* se baseia na ideia básica de [[file:Cálculo proposicional#Argumentos .org][ argumento lógico]], no qual se todas as premissas são verdadeiras, então a conclusão também deve ser verdadeira.
O indutivismo *ingênuo* considera que a experiência é capaz de garantir a veracidade das premissas, ou seja, das leis e teorias científicas. Com base nisso podemos então extrair dessas premissas novas previsões e explicações para eventos através da dedução.
É possível perceber que, apesar de ser um método objetivo e livre de preconceitos ou análises subjetivas, o indutivismo tem uma fundação questionável principalmente no que toca à derivação de teorias através da generalização de observações empíricas. É justamente essa fundação questionável a razão do indutivismo ter sido duramente criticado tanto por [[id:72593630-DB6F-4039-B413-2B468DFBC66C][Karl Popper]] quanto por [[id:2CF712F8-C429-449E-979A-E2B2C114D598][Thomas Kuhn]].

--------------

created: 27/08/2021
