:PROPERTIES:
:ID: 0786cae3-e48b-429c-9459-398590b702a1
:END:
#+title: Inferência estatística
#+filetags: :Popula:

* Inferência estatística
A [[id:4fe88b18-7a39-47e5-b8aa-6010026e83c0][análise descritiva e exploratória de dados]] nos permite interpretar e resumir os dados de uma amostra, porém não dispõe das ferramentas para *inferir* conclusões sobre toda a [[file:Análise descritiva e exploratória de dados#População e amostra.org][população]], para esse fim existe outro método de análise de dados: a /inferência estatística/.
O objetivo da inferência estatística é justamente obter conclusões sobre caraterísticas de interesse de uma *população* com base na informação contida apenas em uma *amostra* dessa população. A inferência estatística pode ser dividida em duas áreas:

- /[[id:68511f23-2d53-499a-a706-0bcaf8c6f332][Estimação de parâmetros]]/: buscar, segundo algum critério, valores que representem adequadamente os parâmetros desconhecidos de uma distribuição de probabilidade com base em uma amostra de observações.
- /[[id:284844c0-c018-4d95-8ca0-a54932b8d4ea][Teste de hipóteses]]/: utilizar a amostra de observações da distribuição de probabilidade para verificar a validade de afirmações sobre valores dos parâmetros desconhecidos.

Ambas as área se baseiam nas [[id:b6e78cf6-3de3-4e47-ad83-c184602c48f4][estatísticas e suas distribuições]], sendo essa a base para toda a inferência estatística.

--------------

created: 14/05/2021

[[file:introducao_inferencia.pdf.org][introducao_inferencia.pdf]]
