:PROPERTIES:
:ID: 0786CAE3-E48B-429C-9459-398590B702A1
:END:
#+title: Inferência estatística
#+filetags: :Popula:

* Inferência estatística
A [[id:4FE88B18-7A39-47E5-B8AA-6010026E83C0][análise descritiva e exploratória de dados]] nos permite interpretar e resumir os dados de uma amostra, porém não dispõe das ferramentas para *inferir* conclusões sobre toda a [[file:Análise descritiva e exploratória de dados#População e amostra.org][população]], para esse fim existe outro método de análise de dados: a /inferência estatística/.
O objetivo da inferência estatística é justamente obter conclusões sobre caraterísticas de interesse de uma *população* com base na informação contida apenas em uma *amostra* dessa população. A inferência estatística pode ser dividida em duas áreas:

- /[[id:68511F23-2D53-499A-A706-0BCAF8C6F332][Estimação de parâmetros]]/: buscar, segundo algum critério, valores que representem adequadamente os parâmetros desconhecidos de uma distribuição de probabilidade com base em uma amostra de observações.
- /[[id:284844C0-C018-4D95-8CA0-A54932B8D4EA][Teste de hipóteses]]/: utilizar a amostra de observações da distribuição de probabilidade para verificar a validade de afirmações sobre valores dos parâmetros desconhecidos.

Ambas as área se baseiam nas [[id:B6E78CF6-3DE3-4E47-AD83-C184602C48F4][estatísticas e suas distribuições]], sendo essa a base para toda a inferência estatística.

--------------

created: 14/05/2021

[[file:introducao_inferencia.pdf.org][introducao_inferencia.pdf]]
