:PROPERTIES:
:ID: 89dfb607-a09a-445d-97be-71301a9dfbe1
:END:
#+title: Inferência na lógica de predicados
#+filetags: :Regras:Argumentos:Leis:

* Inferência na lógica de predicados
Para provar [[file:Cálculo proposicional#Argumentos.org][argumentos]] na lógica de predicados utilizamos as mesmas [[id:09d8c7ad-6d5a-49a2-ab65-3032452eb2eb][técnicas dedutivas]] da [[id:6931da83-27a2-4c30-966c-e7f4627b2819][lógica proposicional]], nos baseando nas [[file:Cálculo proposicional#Regras de inferência.org][regras de inferência]] e [[file:Álgebra da lógica proposicional#Leis de equivalência.org][leis de equivalência]]. Devemos levar em conta também as relações de [[id:321ba6fd-c526-4d8c-9087-4c93510f874a][consequência e equivalência]] específicas à lógica de predicados.
Além das regras já citadas, é necessário introduzir novas regras para lidar especificamente com os /quantificadores/ presentes na lógica de predicados.

** Eliminação (particularização ou instanciação)
A eliminação consiste em, a partir de uma fórmula quantificada, remover o quantificador instanciando (particularizando) a variável que está sendo quantificada.

#+begin_quote
*/Eliminação universal/*
\[
\forall X p(X) \therefore p(c)
\]

#+end_quote

#+begin_quote
*/Eliminação existencial/*
\[
\exists X p(X) \therefore p(c)
\]

#+end_quote

** Introdução (generalização)
A introdução consiste em, a partir de uma fórmula não quantificada, introduzir um quantificador generalizando o predicado.

#+begin_quote
*/Introdução universal/*
\[
p(c) \therefore \forall X p(X)
\]

#+end_quote

#+begin_quote
*/Introdução existencial/*
\[
p(c) \therefore \exists X p(X)
\]

#+end_quote

--------------

created: 12/06/2021

[[file:Regras_inferencia_equivalencia.pdf.org][Regras_inferencia_equivalencia.pdf]]
