:PROPERTIES:
:ID: 0D78366A-F6A7-4422-B4D7-919323CCD826
:END:
#+title: IPA MOC

* Introdução ao pensamento algorítmico
Essa disciplina introduz a base do pensamento computacional e algorítmico. Os dois livros nos quais a disciplina se baseia estão referenciados no final dessa nota. Por enquanto estou decidindo seguir mais com o /Grokking Algorithms/, gostei bastante da proposta e da forma como ele se estrutura. Apesar disso, as notas compilam conteúdo tanto das aulas quanto de ambos os livros, quando necessário.

** Classes
[[id:DA82A778-3A96-4CE6-919F-850F6D942D55][Notes/Backtracking]]

** Book
O livro-base da disciplina é o [[file:GrokkingAlgorithms.pdf.org][Grooking Algorithms]], um livro com várias ilustrações que busca mostrar de forma intuitiva os conceitos de algoritmos.
### Chapter 1
This chapter introduces the basics of algorithms and how to measure the runtime of an algorithm.
[[id:581EAFAF-50CA-4645-9310-C00382DEF78B][Binary search]]
[[id:AC5E75AC-4872-46C2-8942-DB1390A522FE][Big O notation]]

*** Chapter 2
Here we are introduced to the first two basic data structures. We also are presented to our first and more basic sorting algorithm.
[[id:6DB789D2-D84C-44D5-ADDC-0FFE19376404][Arrays and linked lists]]
[[id:192B088B-6E0E-4FB1-8B68-FFC8F5379276][Selection sort]]

*** Chapter 3
This chapter focus only on the topic of recursion, from its core concept to call stacks and so on.
[[id:A858B445-1961-4C2A-AC4F-F468A6F16951][Recursion]]

*** Chapter 4
This chapter focus on using recursion to solve more complex problems and introduces the quicksort algorithm.
[[id:E87A5FAD-8974-4A38-8619-BE697D19F477][Notes/Divide and conquer]]
[[id:7FD05974-6AB4-4F27-8456-0B0A35733D60][Notes/Quicksort]]

*** Chapter 5
Here we are presented to hash tables and its uses.
[[id:6E0F1887-767B-416F-A00A-50633F4C55E3][Hash tables]]
[[id:D5473F8C-BEBE-4A88-9142-76CAA2DD0055][Hash function]]

*** Chapter 6
This chapter presents the concept of graphs and some algorithms to work with them.
[[id:745AE602-A822-4D02-93FF-AC9026050812][Graphs]]
[[id:EABC6191-96BF-45ED-AD6A-F5394C7399E3][Breadth-first search]]

*** Chapter 7
Still in the context of graphs we are presented to new concepts and ways to work with them.
[[id:AE9966D2-1933-4CEB-9976-41B961D8F6EF][Weighted graphs]]
[[id:1D3EB2F7-388C-4FF4-B9A3-F6835F32D17D][Dijkstra's algorithm]]

--------------

created: 10/11/2020
modified: 10/11/2020

[[file:ThinkLikeAProgrammer.pdf.org][ThinkLikeAProgrammer.pdf]]
[[file:GrokkingAlgorithms.pdf.org][GrokkingAlgorithms.pdf]]
