:PROPERTIES:
:ID: 4e7fb41d-872d-4b4a-bd36-24da3d3b0796
:END:
#+title: LM MOC

* Lógica Matemática
A lógica busca formalizar matematicamente o raciocínio, eliminando ambiguidades e criando ferramentas de análise e dedução baseadas em regras bem estabelecidas. Na computação a lógica matemática tem uma especial importância, pois é capaz de modelar em uma uma estrutura dicotômica (binária), capaz de ser processada por computadores. Nessa disciplina foram introduzidos os conceitos básicos da lógica proposicional, bem como a álgebra e o cálculo proposicional. O referencial teórico foi [[file:fundamentoslogicamatematica.pdf .org][ essa apostila]].

** Lógica proposicional
Na primeira parte do curso fomos introduzidos à [[id:6931da83-27a2-4c30-966c-e7f4627b2819][lógica proposicional]], tratando de diversos tópicos que a compõe:

[[id:c1a20b1f-567f-48fa-a573-814eee5412d3][Sintaxe da lógica proposicional]]
[[id:3e618536-d41d-4fde-9a36-7b06bf81b2af][Semântica da lógica proposicional]]
[[id:260f4d65-72b0-48ba-a9c5-0187e8283c28][Consequência e equivalência lógica]]
[[id:933c0eca-6590-4d6a-abc5-0c37f330100c][Álgebra da lógica proposicional]]
[[id:215dd1f0-b6d1-466e-8e8c-86fbd475984d][Cálculo proposicional]]
[[id:09d8c7ad-6d5a-49a2-ab65-3032452eb2eb][Técnicas dedutivas]]

** Lógica de predicados
Nessa parte do curso estudamos a [[id:a3dd607a-e5e1-4014-a96c-7153fe08c507][lógica de predicados]], uma forma mais complexa e poderosa de representação.

[[id:43fa5869-93fe-4194-826d-fa9a41d64e7e][Sintaxe da lógica de predicados]]
[[id:051f4c5d-1ed4-41bc-92a6-cbdab7847060][Semântica da lógica de predicados]]
[[id:321ba6fd-c526-4d8c-9087-4c93510f874a][Consequência e equivalência lógica na lógica de predicados]]
[[id:89dfb607-a09a-445d-97be-71301a9dfbe1][Inferência na lógica de predicados]]
[[id:c3abd1a6-be83-4152-9872-bcaf33f6d48e][Unificação e Substituição]]
[[id:c85ace88-0a8f-4055-8fc5-1f9e62f89b04][Forma Normal Conjuntiva na Lógica de Predicados]]
[[id:6939dcf6-1da4-440b-847f-c0366372db5d][Resolução na lógica de predicados]]

--------------

created: 06/05/2021
