:PROPERTIES:
:ID: 6931DA83-27A2-4C30-966C-E7F4627B2819
:END:
#+title: Lógica proposicional

* Lógica proposicional
A lógica proposicional tem o objetivo mapear o conhecimento em uma linguagem sem ambiguidades processável matematicamente.
Existem dois princípios fundamentais na lógica proposicional:

- *Princípio da não contradição: * uma proposição não pode ser verdadeira e falsa ao mesmo tempo.
- *Princípio do terceiro excluído: * toda proposição ou é verdadeira ou falsa, não há terceiro valor possível.

É importante antes de mais nada entender o conceito de *proposição*, pois as proposições são as estruturas básicas que compõe a lógica proposicional.
Uma /proposição/ é um enunciado completo que exprime um pensamento de sentido completo no qual podemos atribuir um /valor-verdade/. Proposições afirmam fatos ou exprimem juízos que podem (ou não) representar a realidade. Atribuímos às proposições /valores lógicos/, que podem ser /verdadeiro(\(V\))/ ou /falso(\(F\))/.
Uma proposição pode ser classificada em um dos dois tipos:

- Atômica (fórmula atômica): formada por uma e somente uma proposição, não possui nenhum conectivo lógico.
- Composta (fórmula composta): formada por duas ou mais proposições atômicas ligadas por conectivos lógicos.

Como qualquer outra linguagem, a lógica proposicional é composta por [[id:C1A20B1F-567F-48FA-A573-814EEE5412D3][sintaxe]] e [[id:3E618536-D41D-4FDE-9A36-7B06BF81B2AF][semântica]].

--------------

created: 08/05/2021
