:PROPERTIES:
:ID: 9687416A-352B-4614-AE94-65C7B84B9CEB
:END:
#+title: Particípio

* Participium
O particípio é uma /forma nominal/ de um verbo, ou seja, um verbo que tem sua função modificada para funcionar como um nome na oração. Em latim o particípio é um verbo na forma de [[id:8E7935A3-F353-4F17-8037-1D821626A14E][adjetivo]].
É interessante destacar que o particípio preserva as funções verbais, ou seja, é possível que um particípio leve um objeto no acusativo.
O particípio se declina como na [[file:Declinações dos adjetivos#3 Dēclīnātiō tertia.org][terceira declinação dos adjetivos]], porém seus sufixos variam um pouco, então decidi deixar a tabela de declinação especificamente aqui. Vale lembrar que antes dos sufixos da tabela o particípio leva a terminação verbal de sua conjugação, que nesse caso são /ā, ē, ē, iē/ para as terminações em /ns/ e /a, e, e, ie/ para as terminações que contém a letra /t/. Note que aqui as terminações da segunda e terceira conjugação são iguais em ambos os casos.

Singulāris

|        | masc./fēm. | neutr.  |
|--------+------------+---------|
| *nōm.* | -ns        | -ns     |
| *acc.* | -nt|em     | -ns     |
| *gen.* | -nt|is     | -nt|is  |
| *dat.* | -nt|ī      | -nt|ī   |
| *abl.* | -nt|e/ī    | -nt|e/ī |

Plūrālis

|        | masc./fēm. | neutr.   |
|--------+------------+----------|
| *nōm.* | -nt|ēs     | -nt|ia   |
| *acc.* | -nt|ēs     | -nt|ia   |
| *gen.* | -nt|ium    | -nt|ium  |
| *dat.* | -nt|ibus   | -nt|ibus |
| *abl.* | -nt|ibus   | -nt|ibus |

--------------

created: 01/04/2021
modified: 01/04/2021
