:PROPERTIES:
:ID: 1e7510f3-6ea9-405e-b976-9be35f94a90e
:END:
#+title: Teoria dos Números

* Teoria dos Números
A teoria dos números se dedica ao estudo dos números inteiros e suas propriedades. Esse campo da matemática é de fato muito extenso, portanto aqui ficam enunciadas apenas algumas propriedades e conceitos básicos dos números inteiros.

** Divisibilidade
A divisibilidade é um conceito básico mas que serve para compor muitos outros conceitos e propriedades relacionadas a números inteiros.

#+begin_quote
Dados dois inteiros \(a\) e \(b\) tal que \(b \neq 0\), dizemos que \(b\) *divide* \(a\) se há um inteiro \(c\) tal que \(a=bc\). Essa relação é denotada por \(b | a\).

#+end_quote

A partir da decomposição do conceito de divisibilidade, obtém-se o *teorema da divisão*.

#+begin_quote
Dados dois inteiros \(a,b \in \mathbb{Z}\) com \(b > 0\), existe *um único par* de inteiros \((q,r)\) tais que:
\[
a = qb + r \qquad \text{ e } \qquad 0 \leq r \leq b
\]
O inteiro \(q\) é chamado de /quociente/ da divisão, enquanto \(r\) é chamado de /resto/.

#+end_quote

** Máximo divisor comum (MDC)

#+begin_quote
Dados dois inteiros \(a,b \in \mathbb{Z}\), o máximo divisor comum é o *maior inteiro que divide* \(a\) e \(b\).

#+end_quote

É possível calcular o /MDC/ de dois números através do /Algoritmo de Euclides/, que pode ser definido da seguinte forma:

#+begin_example
mdc a b =
  r = a mod b
  if r = 0 then b else mdc b r
#+end_example

** Números relativamente primos

#+begin_quote
Dados dois inteiros \(a\) e \(b\), dizemos que eles são *relativamente primos* (ou primos entre si) se e somente se \(mdc(a,b) = 1\).

#+end_quote

** Teorema fundamental da aritmética

#+begin_quote
Se \(n\) é um número inteiro positivo, então pode-se decompor \(n\) em um produto de números primos.

#+end_quote

--------------

created: 20/10/2021
