:PROPERTIES:
:ID: de95c1eb-6f0d-45e5-adea-aed5a7333e5d
:END:
#+title: Árvore

* Árvore
Árvores são um tipo específico de [[id:c3d5cf02-7c9a-470b-ae4b-c49c7ef7e6ca][grafo]], sendo utilizadas para modelar uma classe muito grande de problemas computacionais.

Uma /árvore/ é um grafo /conexo acíclico/. Note que um grafo com um vértice e nenhuma aresta é, por definição, uma árvore.

As árvores possuem propriedades, algumas das quais são listadas aqui:

- Todo subgrafo conexo de uma árvore é também uma árvore.
- Há um único caminho entre cada par de vértices.
- Adicionar uma aresta entre dois nós não adjacentes em uma árvore cria um grafo com um ciclo.
- Toda aresta em uma árvore é uma aresta de corte.
- O número de vértices em uma árvore é uma unidade maior do que o número de arestas

** Árvore geradora
Uma /árvore geradora/ de um grafo \(G\) é um /subgrafo gerador/ de \(G\) que é uma árvore.

** Floresta
Uma /floresta/ é um /grafo acíclico/, ou seja, é um grafo cujas componentes conexas são árvores.

--------------

created: 17/11/2021
