:PROPERTIES:
:ID: DE95C1EB-6F0D-45E5-ADEA-AED5A7333E5D
:END:
#+title: Árvore

* Árvore
Árvores são um tipo específico de [[id:C3D5CF02-7C9A-470B-AE4B-C49C7EF7E6CA][grafo]], sendo utilizadas para modelar uma classe muito grande de problemas computacionais.

Uma /árvore/ é um grafo /conexo acíclico/. Note que um grafo com um vértice e nenhuma aresta é, por definição, uma árvore.

As árvores possuem propriedades, algumas das quais são listadas aqui:

- Todo subgrafo conexo de uma árvore é também uma árvore.
- Há um único caminho entre cada par de vértices.
- Adicionar uma aresta entre dois nós não adjacentes em uma árvore cria um grafo com um ciclo.
- Toda aresta em uma árvore é uma aresta de corte.
- O número de vértices em uma árvore é uma unidade maior do que o número de arestas

** Árvore geradora
Uma /árvore geradora/ de um grafo \(G\) é um /subgrafo gerador/ de \(G\) que é uma árvore.

** Floresta
Uma /floresta/ é um /grafo acíclico/, ou seja, é um grafo cujas componentes conexas são árvores.

--------------

created: 17/11/2021
