#+title:Cálculo Numérico

Cálculo numérico (ou análise numérica), é o ramo do cálculo que estuda algoritmos de aproximação numérica para diversos problemas da matemática.

* Erros e Sistemas de Ponto Flutuante
Em se tratando de métodos de aproximação, a existência de erros é inevitável. Portanto, são necessários métodos para entender o comportamento desses erros e estabelecer resultados confiáveis para os mesmos.

Se em uma dada medida o valor esperado é $x$ e o valor efetivamente medido (ou aproximado) é $x_0$, então o *erro absoluto* é dado por

$$ |x-x_0| $$

e o *erro relativo* é

$$ \frac{|x-x_0|}{x} $$

Note que essa definição de erro depende do valor esperado (ou o valor real, não aproximado). O problema é que muitas vezes esse valor não é conhecido e não pode ser obtido facilmente. Entretanto, é possível obter um *limitante superior* para os erros que garante que o erro não excederá um determinado valor.

Se sabemos que $x_m < x < x_M$, então a aproximação for dada por $\frac{x_M + x_m}{2}$, o *erro absoluto* está limitado superiormente por

$$ \frac{x_M-x_m}{2} $$

e como $x_m < x$, o *erro relativo* está limitado superiormente por

$$ \frac{x_M - x_m}{2x_m} $$

** Erros de representação
Muitas vezes os erros podem surgir de sua representação. Em geral, a representação de um número real $x$ em uma base $b$ se dá através de uma soma (possivelmente infinita) de potências de $b$:

$$
x=s \sum_{k = - \infty}^{N} x_k b^k
$$

onde $b, x_k \in \mathbb{N}, N \in \mathbb{Z}, b>1, x_N > 0, 0 \leq x_k < b$ e $s$ é o sinal de $x$.   Nessas condições, garante-se que todo número real tem uma *única representação* na base $b$.

*** Dígitos significativos corretos
Dado um número $x$ com sua representação representada por $(x_Nx_{N-1}\dots x_1x_0,x_{-1}x_{-2}\dots})_b$, se o erro absoluto é menor que $\frac{1}{2}b^m$, dizemos que $x_m$ é um dígito significativo exato.

*** Sistemas de Ponto Flutuante
Os /sistemas de ponto flutuante (SPF)/ consistem em uma maneira padronizada de representar números em uma base. Um SPF assume que o número de dígitos a serem utilizados é fixo e que os expoentes permitidos estão em um intervalo bem definido.

Um SPF é composto de $4$ números inteiros $(b, d, e_m, e_M)$, onde $b$ é a base, $d$ é o número de dígitos (depois da vírgula) da representação, e os expoentes devem estar entre os limites inferior e superior $e_m$ e $e_M$.

Note que se o número tiver mais dígitos que $d$, apenas os $d$ mais significativos são representados. Veja também que caso o número só possa ser representado na forma normal com um expoente fora do intervalo $[e_m, e_M]$ ele não pode ser representado no SPF. Dessa forma, *nem todo número real* pode ser *representado* exatamente em um dado SPF, e é possível que *números diferentes* tenham a *mesma representação*.

Um número qualquer, diferente de $0$ representado em um dado SPF $(b, d, e_m, e_M)$ tem a forma:

$$s 0, d_1d_2d_3\dots d_d \times b^e$$

onde $s$ é o sinal, $d_1 \dots d_d$ é a /mantissa/, com $d_1 \neq 0$ e $e_m\leq e \leq e_M$.

Os sistemas de ponto flutuante possuem problemas inerentes de precisão que se tornam mais claros ainda na aplicação de operações sobre os números. É possível que o produto de dois números não exista no SPF, que as propriedades básicas das operações entre números reais não sejam satisfeitas, entre outros problemas que resultam do uso de apenas um subconjunto dos reais para representação numérica.

* Resolução de sistemas lineares
* Resolução de sistemas não lineares
* Aproximação de funções
* Integração numérica de funções
* Resolução de sistemas de equações diferenciais
