#+title:Inteligência Artificial
A Inteligência Artificial é o ramo da ciência da computação relacionado com a automação do comportamento inteligente, operando através da criação de modelos para a inteligência e implementando sistemas computacionais baseados nesses modelos.

* Resolução de problemas por Busca
A resolução de problemas por busca consiste em modelar um problema usando uma representação do mundo baseada em *estados* e aplicar um *algoritmo de busca* sobre esses estados para encontrar uma solução para o problema.

** Representação de problemas
Para a resolução de problemas por busca é necessário definir o problema a ser resolvido. Essa definição é composta por dois grupos de elementos essenciais:
- *estados* que representam o mundo
- *ações* que provocam a alteração de um estado para outro

Nesse tipo de resolução assume-se que o ambiente no qual o problema se insere é:
- *observável*: o estado atual é conhecido.
- *discreto*: existe apenas um número finito de ações possíveis em cada estado.
- *conhecido*: o estado resultante de cada ação é conhecido.
- *determinístico*: cada ação leva a apenas um estado.

Para definir um problema são necessários 5 componentes:
- *Estado inicial:* estado a partir do qual a busca se inicia.
- *Ações (ou operadores):* possíveis ações aplicadas a cada estado.
- *Modelo de transição:* descrição do resultado de cada ação com base no estado atual e na ação tomada.
- *Teste final:* condições que determinam se um estado é o objetivo.
- *Custo do caminho:* função que atribui um custo ao caminho, mede a qualidade da solução.

Uma *solução* é uma sequência de ações que vai do estado inicial ao estado objetivo.

** Algoritmos de busca
Com um problema formulado, a solução consiste em realizar uma busca no espaço de estados até encontrar uma sequência de ações que atinjam o estado objetivo. O processo de busca acaba por construir uma *árvore de busca*, cuja raiz é o estado inicial, os nós são os demais estados, as ligações entre nós são as ações e a solução é o caminho da raiz até o nó final (estado objetivo).

No geral os algoritmos de busca possuem a mesma estrutura básica, que consiste em expandir os nós a partir das ações possíveis, gerando novos nós e repetir o processo até que se atinja o nó final. Apesar disso, os algoritmos diferem na *estratégia de busca*, que determina o critério usado para selecionar o próximo nó a ser expandido na árvore de busca.

*** Busca desinformada
*** Busca informada

* Representação de Conhecimento e Raciocínio

* Aprendizado de Máquina
