:PROPERTIES:
:ID:       cd7c7e8f-a6b3-4a2a-b3f9-181db91c3834
:END:
#+title: 2023-07-10
* Cultura e signos
Uma cultura é um conjunto de indivíduos que cultua um mesmo signo, que é um conjunto de ideias materiais ou abstratas que podem ser representadas por meio de um símbolo em uma linguagem.
Usamos os símbolos para produzir signos e movê-los em um plano de múltiplas dimensões contínuas, sendo a comunicação uma forma de tentar produzir estes mesmos signos na mente de um terceiro. Com a comunicação, jamais há a garantia de produção de um exato mesmo signo, pois um signo por definição não possui a operação de igualdade, pois ela é inverificável.
Chamamos de interpretação o processo que ocorre no interlocutor ao processar os símbolos da mensagem e deles derivando um signo. Esse processo também é afetado por signos e símbolos do interlocutor, como memórias, estado mental, stress etc.
A analogia é uma técnica de comunicação que consiste em, partindo de um símbolo conhecido pelo interlocutor, induzí-lo a outro signo estabelecendo uma comparação.
