:PROPERTIES:
:ID:       cb19beb6-863a-45ba-b172-8040cd461cad
:END:
#+title: 2023-08-11
* Plan the day
Hoje tenho aula de PDI pela parte da manhã, então meu tempo para fazer outras coisas vai ser um tanto limitado. Espero conseguir resolver o problema de encoding do SMS pela parte da tarde, e então programar um pouco com a Fer, talvez fazer uma calculadora juntos.

[[id:8114d328-0228-4d84-9bad-ded99c223b95][Ontem]] foi um dia bem legal, consegui fazer coisas legais no trampo e à noite saí com a Le e o Fran. É muito bom ter amigos com aspirações e objetivos parecidos.

Como ontem eu cheguei tarde em casa não tive a oportunidade de planejar o dia de hoje, então acho que vale a reflexão sobre como vou planejar hoje. Sinto que tendo a ser bastante otimista de manhã. Apesar disso, acho que os objetivos que traço pela manhã ainda são realistas, mas me falta brio.

** DONE Resolver bug de encoding do SMS
CLOSED: [2023-08-12 Sat 09:57]
scheduled: <2023-08-11 Fri>
Aparentemente tem algo de estranho com o que estamos recebendo do SMPP, talvez seja um fix maior. Apesar disso conseguimos entender bem o problema inicial e identificar que na verdade não é um problema do nosso lado.
** DONE Programar uma calculadora com a Fer
CLOSED: [2023-08-12 Sat 09:57] SCHEDULED: <2023-08-11 Fri>
Começamos a fazer e vamos terminar amanhã
** DONE Trabalhar na rotina de compartilhamento
CLOSED: [2023-10-07 Sat 10:56] SCHEDULED: <2023-08-11 Fri>
