:PROPERTIES:
:ID:       8114d328-0228-4d84-9bad-ded99c223b95
:END:
#+title: 2023-08-10
* Plan for today
Yesterday I have set up some basic journaling capabilities in my emacs using org-roam, today the focus is to continuing exploring those capabilities, focusing on capture templates and dashboard keybindings display.

*** DONE Fix my OTP Install
CLOSED: [2023-08-10 Thu 08:12]
Although I've fixed it, Elixir-ls doesn't seem to work
*** DONE Setup dashboard commands to interact with org-agenda and journal entries
CLOSED: [2023-08-10 Thu 07:51]
The idea is to make it easier to access those commands so I can use them more often.
*** CANCELLED Setup capture templates
CLOSED: [2023-09-06 Wed 08:40]
See entry about that on [[file:~/docs/org/todo.org]]
*** DONE Fix Python template on project
CLOSED: [2023-08-10 Thu 12:16]
It's really annoying that the shebang is added on every Python file. I've managed to configure it so the template is only used on files that do not belong to a project.

#+begin_src emacs-lisp
(set-file-template! "\\.py$" :project t)
#+end_src
* Seeds CLI
Hoje criei uma CLI simples para a criação e execução de seeds de banco de dados para o projeto da Trópico HSS. Foi uma experiência bastante interessante. Tive um grande auxílio do ChatGPT para a interação com as APIs do filesystem e de parsing de argumentos para o CLI. A criação dos arquivos de seed é feita com base em um template [[https://www.makotemplates.org/][Mako]], a mesma ferramenta utilizada pelo Alembic. Achei bastante interessante reaproveitar esse conceito, pois foi possível criar uma experiência final razoavelmente amigável sem introduzir nenhuma dependência externa.
