:PROPERTIES:
:ID:       fee588df-2e8e-4615-94c9-0364374007c9
:END:
#+title: 2023-11-06

* Morning entry
** DONE Bromelia event system
CLOSED: [2023-11-06 Mon 16:26]
* Investimento passivo
Ultimamente tenho pensando em aplicar a [[https://en.wikipedia.org/wiki/Pareto_principle][Regra de Pareto]] em diversas áreas da vida, e os investimentos são um cenário no qual eu acredito que ela é particularmente eficiente.

Investir através de ETFs de índices é extremamente mais simples e proporciona uma exposição diversificada ao mercado como um todo. Do ponto de vista psicológico, penso que investir apenas em ETFs seja algo equivalente a um "estoicismo dos investimentos". Essa ideia decorre do fato de que, ao investir em ETFs diversificados, estamos expostos ao a mercado como um todo, diminuindo o impacto de fatores externos que não estão sob nosso controle.

Outro ponto extremamente importante é a simplicidade não só no momento de estudar e entender o investimento, mas na hora de fazer a manutenção tributária desse investimento. Gastei bastante tempo fazendo uma planilha para controlar os investimentos mas ainda assim sempre tenho dúvidas e receios com relação ao pagamento de impostos. Ter apenas um punhado de ETFs (ou apenas um) parece simplificar bastante isso.

#+begin_quote
complexity very, very bad

given choice between complexity or one on one against t-rex, grug take t-rex: at least grug see t-rex
#+end_quote

https://www.bogleheads.org/wiki/Bogleheads%C2%AE_investment_philosophy_for_non-US_investors
* Tributos de investimentos no exterior
Na reforma tributária da taxação sobre investimentos no exterior a ideia inicial era aplicar uma tabela progressiva de 0 a 22.5% de acordo com o tamanho do lucro no ano. Isso significa que aqueles que têm mais atrimônio pagariam uma alíquota mais alta de impostos. A reforma passou por uma subemenda que remove o componente progressivo e fixa a taxa em 15% independente do lucro. Interessante ver como claramente a mudança desfavorece aqueles que têm menos patrimônio mas no final das contas o valor arrecadado pelo governo deve ser o mesmo, portanto eles não têm incentivo para não aprovar a subemenda.
