:PROPERTIES:
:ID:       98ace2db-d6dc-46b2-9b11-ba17b6d3c0d9
:END:
#+title: 2023-06-27
* Deep work and intensity
Reading /Deep Work/ I came about a chapter in which Theodore Roosevelt is used as an example of focus and working with intensity. I find very interesting that all these famous polymaths have that variable in common: *intensity*. Interestingly enough, lately my training philosophy is turning much more towards consistency and intensity instead of pure volume, which seems to be the norm.

In fact, doing things with quality, focus and commitment allows for extracting great value for whatever you are doing. And perhaps even more important, it frees up time so you can diversify your activities, and therefore explore life in both more depth and breath than you previously though was possible.

Why don't I commit to this? What am I fearing? What's holding me back? Identifying these elements and dealing with them is an important step towards improvement, but the first step, as noted in /Atomic Habits/, is to identify what is it that I want to achieve, what is the *identity* that I want to pursue?
