:PROPERTIES:
:ID:       856567a0-553e-43d8-ae90-66061ad93262
:END:
#+title:Gramática

Uma gramática é um formalismo axiomático de geração que permite *derivar* todas as palavras da [[id:70808c19-0237-4a2e-8a09-d003667c1278][linguagem]] que representa. Pode-se definir uma gramática como uma quádrupla ordenada $G = (V, T, P, S)$ tais que:

- $V$ é um conjunto finito de [[id:f8a4e91c-078f-433c-9be4-fb1f4b9d064e][símbolos]] *variáveis* ou não-terminais;
- $T$ é um conjunto finito de símbolos *terminais*  (disjunto de $V$);
- $P$ é uma relação finita (conjunto finito de pares) na forma $(V \cup T)^+ \to (V \cup T)^*$  denominada *regras de produção*;
- $S$ é um elemento de $V$ chamado *variável inicial*.

As regras de produção definem as condições de geração das palavras da linguagem. A aplicação sucessiva de regras de produção permite derivar todas as palavras da linguagem representada pela gramática. Sendo assim, dada uma gramática $G = (V,T,P,S)$, uma linguagem gerada por $G$, denotada por $L(G)$ é composta por todas as [[id:2e1e038b-f30b-48bb-8d43-0fdae3f0afba][palavras]] de *símbolos terminais* deriváveis a partir do símbolo inicial $S$, ou seja:

$$
L(G) = \{w \in T^* | S \Rightarrow^+ w\}
$$

Duas gramáticas $G1$ e $G2$ são equivalentes se e somente se ambas geram a mesma linguagem, ou seja, se $L(G1) = L(G2)$.

Uma cadeia $w \in T^*$ é dita uma *sentença* da gramática $G=(V,T,P,S)$ se e somente se $S \Rightarrow^* w$, ou seja, se $w$ é uma cadeia formada apenas de símbolos terminais e pode ser obtida a partir do símbolo $S$ da gramática $G$ por meio de sucessivas derivações.

Uma cadeia $\alpha \in (V \cup T)^*$ é dita *forma sentencial* da gramática $G=(V,T,P,S)$ se e somente se $S \Rightarrow^* \alpha$, ou seja, $\alpha$ é uma palavra formada por símbolos variáveis ou terminais (ou ambos). Sendo assim, uma forma sentencial é um dos passos intermediários para alguma sentença gerada pela gramática, ou a própria sentença.
