:PROPERTIES:
:ID:       3727e543-aa79-4bb7-b283-ee7365e000ce
:END:
#+title:Projeto e Análise de Algoritmos

Projetar algoritmos eficientes requer, além de uma boa intuição, métodos formais para entender e analisá-los. Em computação, geralmente estamos interessados no comportamento *assintótico* dos algoritmos, ou seja, em como se comportam quando o tamanho de sua entrada tende ao infinito. Sendo assim, a [[id:20ecb870-62df-41a4-b342-115f6368166e][análise assintótica]] se mostra como uma das mais importantes e fundamentais ferramentas na análise de algoritmos.

Para projetar algoritmos assintoticamente eficientes, geralmente são empregadas algumas técnicas já conhecidas. Algumas técnicas muito conhecidas e comumente utilizadas para resolver problemas de otimização (que consistem em maximizar ou minimizar algum aspecto do problema) incluem:

- [[id:80e35d86-8bcb-4c0f-92e6-039151f66789][Dividir para Conquistar]]
- [[id:41602087-1763-458b-950c-466c1636157b][Programação Dinâmica.]]
- [[id:f2fa433c-ee8c-4330-86ac-84c7222d91b4][Greedy Algorithms]]

Vale notar que as técnicas não são mutualmente exclusivas, ou seja, podem ser combinadas e utilizadas em conjunto a depender das características do problema a ser resolvido.
